### ISSUE TITLE
Rabin - Karp algorithm

### ISSUE THREAD

**Issue by ritweekraj2802** [namishkhanna/hacktoberfest2021#42]
I want to add this problem .
Please assign me this problem.
Thank you

**Comment by namishkhanna** [comment]
Okk

**Comment by ritweekraj2802** [comment]
Please accept my PR i send to you
Thank you

**Comment by ritweekraj2802** [comment]
@namishkhanna Please accept my PR i send to you

I have participated in HACKTOBERFEST2021 so i need this PR
Thank you
